
USE STAGE_TABLES_DB_2
GO


CREATE DATABASE STAGE_TABLES_DB_2

USE STAGE_TABLES_DB_1
GO 

CREATE SCHEMA BOOKING_S2
CREATE SCHEMA TIPPING_S2



-- SELECT DISTINCT Job No  
-- 209

WITH DistinctJobs AS
(
    SELECT * ,
        ROW_NUMBER() OVER(
            PARTITION BY [Job No] ORDER BY [Job No]) AS 'RowNum' 
    FROM [STAGE_TABLES_DB_1].[BOOKING].[STAGE_TABLE_1]

)


SELECT TOP 3 * INTO #TempTable
FROM DistinctJobs
WHERE RowNum = 1


ALTER TABLE #TempTable
DROP COLUMN [RowNum]


SELECT * INTO [STAGE_TABLES_DB_2].[BOOKING_S2].[STAGE_TABLE_2_BOOKING]
FROM #TempTable
DROP TABLE #TempTable

Select TOP 3 *
FROM [STAGE_TABLES_DB_1].[BOOKING].[STAGE_TABLE_1]
WHERE [STAGE_TABLES_DB_1].[BOOKING].[STAGE_TABLE_1].[Latitude] = 0
/* Get results and drop temp table */



-- WHERE [BOOKING].[STAGE_TABLE_1].[Date] >= '20200320'
--     AND [BOOKING].[STAGE_TABLE_1].[Date] <= '20210228'
--     AND [BOOKING].[STAGE_TABLE_1].[Customer number] = 1825.003



