
USE STAGE_TABLES_DB_1
GO

CREATE SCHEMA TEST_ERROR_SCH

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = 'ERROR_1'
AND INFORMATION_SCHEMA.COLUMNS.TABLE_SCHEMA = 'ITERATE_SEEK_ERROR'
AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = 'Price'


SELECT * ,except  [TABLE_NAME]
FROM INFORMATION_SCHEMA.COLUMNS


SELECT * INTO #TempTable
FROM INFORMATION_SCHEMA.COLUMNS
ALTER TABLE #TempTable
DROP COLUMN [TABLE_NAME]
/* Get results and drop temp table */
SELECT [TABLE_SCHEMA] FROM #TempTable
GROUP BY #TempTable.[TABLE_SCHEMA]
DROP TABLE #TempTable


-- GROUP BY INFORMATION_SCHEMA.COLUMNS.TABLE_NAME

-- WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = 'STAGE_TABLE_1'
-- AND INFORMATION_SCHEMA.COLUMNS.TABLE_SCHEMA = 'BOOKING'
-- AND INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME = 'Price'


SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = 'STAGE_TABLE_1'

SELECT count(*) 
FROM 
ITERATE_SEEK_ERROR.error_1


CREATE SCHEMA ITERATE_SEEK_ERROR


SELECT * 
FROM 
ITERATE_SEEK_ERROR.ERROR_1

TRUNCATE TABLE ITERATE_SEEK_ERROR.ERROR_1


SELECT DISTINCT [Job No], * 
FROM [BOOKING].[STAGE_TABLE_1]
WHERE [BOOKING].[STAGE_TABLE_1].[Date] >= '20200320'
AND [BOOKING].[STAGE_TABLE_1].[Date] <= '20210221'
AND [BOOKING].[STAGE_TABLE_1].[Customer number] = 1825.003


-- [Job No], 
-- 271
SELECT DISTINCT count (*) 
FROM [BOOKING].[STAGE_TABLE_1]
WHERE [BOOKING].[STAGE_TABLE_1].[Date] >= '20200320'
AND [BOOKING].[STAGE_TABLE_1].[Date] <= '20210221'
AND [BOOKING].[STAGE_TABLE_1].[Customer number] = 1825.003


-- SELECT DISTINCT Job No  
-- 209
WITH DistinctJobs AS
(
    SELECT * ,
        ROW_NUMBER() OVER(
            PARTITION BY [Job No] ORDER BY [Job No]) AS 'RowNum' 
    FROM [BOOKING].[STAGE_TABLE_1]
    WHERE [BOOKING].[STAGE_TABLE_1].[Date] >= '20200320'
    AND [BOOKING].[STAGE_TABLE_1].[Date] <= '20210228'
    AND [BOOKING].[STAGE_TABLE_1].[Customer number] = 1825.003

)
SELECT *
FROM DistinctJobs
WHERE RowNum = 1
ORDER BY [DATE] DESC





SELECT COUNT(DISTINCT [Job No] )
FROM [BOOKING].[STAGE_TABLE_1]
WHERE [BOOKING].[STAGE_TABLE_1].[Date] >= '20200320'
AND [BOOKING].[STAGE_TABLE_1].[Date] <= '20210221'
AND [BOOKING].[STAGE_TABLE_1].[Customer number] = 1825.003


SELECT count(*) 
FROM [BOOKING].[STAGE_TABLE_1]
WHERE [BOOKING].[STAGE_TABLE_1].[Job No] >= 1825
AND [BOOKING].[STAGE_TABLE_1].[Job No] <= 1825.1



-- SELECT Count(*) AS DistinctCountries
-- FROM (SELECT DISTINCT Country FROM Customers);

-- SELECT 
-- [ID],[SKU],[PRODUCT]
-- FROM [TestData] 
-- WHERE ([PRODUCT] = 
-- (SELECT DISTINCT [PRODUCT] FROM [TestData] WHERE ([SKU] LIKE 'FOO-%')) 
-- ORDER BY [ID]